version: '3.0'
services:
  zookeeper:
    image: wurstmeister/zookeeper

    ports:
      - "2181:2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.26.1.62 # Your docker host IP. Do not use localhost or 127.0.0.1 as the host ip if you want to run multiple brokers.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - zookeeper
  web:
    image: elkozmon/zoonavigator-web:0.6.1
    # container_name: zoonavigator-web
    ports:
     - "8000:8000"
    environment:
      WEB_HTTP_PORT: 8000
      API_HOST: "api"
      API_PORT: 9000
    depends_on:
     - api
    restart: always
  api:
    image: elkozmon/zoonavigator-api:0.6.1
    # container_name: zoonavigator-api
    environment:
      API_HTTP_PORT: 9000
    restart: always
    depends_on:
     - zookeeper