version: '2.4'
services:
  server:
    image: isthisdesign/onec:8.3.14.1630-bionic
    # Будет использовано для определения имени рабочего сервера
    # Для "прямого" доступа устанавливаем равным имени докерхоста
    hostname: centosDocker
    command:
      bash -c "echo \"192.168.1.118 centosDocker\" >> /etc/hosts && cat /etc/hosts && /opt/1C/v8.3/x86_64/ragent -d /srvinfo"
    ports:
      - 1540:1540
      - 1541:1541
      - 1560-1591:1560-1591
    networks:
      - onec-net

  web:
    image: isthisdesign/onec:8.3.14.1630-bionic
    command: >
      bash -c "/opt/1C/v8.3/x86_64/webinst -apache24 -wsdir sample -dir /var/www/sample -connstr \"Srvr=server;Ref=sample;\"
      && /usr/sbin/apache2ctl -DFOREGROUND"
    ports:
      - 80:80
    networks:
      - onec-net

  ras:
    image: isthisdesign/onec:8.3.14.1630-bionic
    command:
      "/opt/1C/v8.3/x86_64/ras cluster --port=1545 server:1540"
    ports:
      - 1545:1545
    networks:
      - onec-net   

  db:
    image: silverbulleters/ya-docker-postgresql-1c:10.6
    ports:
      - 5432:5432
    networks:
      - onec-net
    environment:  
      - DEBUG=false
      - DB_NAME=powa,mamonsu
      - POWA_DATABASE=powa
      - PG_MAX_CONNECTION=100
      - PG_TIMEZONE=Europe/Moscow
      - PG_PASSWORD=postgres
  jenkins:
    image: 'bitnami/jenkins:2'
    ports:
      - '8080:8080'
      - '9088:9088'
      - '443:8443'
      - '50000:50000'
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
    volumes:
      - 'jenkins_data:/bitnami'
    networks:
      - onec-net
networks:
  onec-net:
volumes:
  jenkins_data:
    driver: local  